INSERT INTO CUSTOMER(ID, ADRESS,CREATED_AT,EMAIL,NAME) VALUES(CUSTOMER_S.NEXTVAL,'Istanbul',CURRENT_TIMESTAMP()-1,'a@gmail.com','Deneme1');
INSERT INTO CUSTOMER(ID, ADRESS,CREATED_AT,EMAIL,NAME) VALUES(CUSTOMER_S.NEXTVAL,'Istanbul',CURRENT_TIMESTAMP()-2,'b@gmail.com','Deneme2');
INSERT INTO CUSTOMER(ID, ADRESS,CREATED_AT,EMAIL,NAME) VALUES(CUSTOMER_S.NEXTVAL,'Istanbul',CURRENT_TIMESTAMP()-3,'c@gmail.com','Deneme3');
INSERT INTO CUSTOMER(ID, ADRESS,CREATED_AT,EMAIL,NAME) VALUES(CUSTOMER_S.NEXTVAL,'Istanbul',CURRENT_TIMESTAMP()-4,'d@gmail.com','Deneme4');
INSERT INTO CUSTOMER(ID, ADRESS,CREATED_AT,EMAIL,NAME) VALUES(CUSTOMER_S.NEXTVAL,'Istanbul',CURRENT_TIMESTAMP()-5,'e@gmail.com','Deneme5');
INSERT INTO CUSTOMER(ID, ADRESS,CREATED_AT,EMAIL,NAME) VALUES(CUSTOMER_S.NEXTVAL,'Istanbul',CURRENT_TIMESTAMP()-6,'f@gmail.com','Deneme6');
INSERT INTO CUSTOMER(ID, ADRESS,CREATED_AT,EMAIL,NAME) VALUES(CUSTOMER_S.NEXTVAL,'Istanbul',CURRENT_TIMESTAMP()-7,'g@gmail.com','Deneme7');
INSERT INTO CUSTOMER(ID, ADRESS,CREATED_AT,EMAIL,NAME) VALUES(CUSTOMER_S.NEXTVAL,'Istanbul',CURRENT_TIMESTAMP()-8,'h@gmail.com','Deneme8');

INSERT INTO BOOK(ID, AUTHOR,CREATED_AT,NAME,STOCK,PRICE,VERSION) VALUES(BOOK_S.NEXTVAL,'Yazar1',CURRENT_TIMESTAMP()-1,'Kitap1',100,5, 0);
INSERT INTO BOOK(ID, AUTHOR,CREATED_AT,NAME,STOCK,PRICE,VERSION) VALUES(BOOK_S.NEXTVAL,'Yazar2',CURRENT_TIMESTAMP()-2,'Kitap2',50,10,0);
INSERT INTO BOOK(ID, AUTHOR,CREATED_AT,NAME,STOCK,PRICE,VERSION) VALUES(BOOK_S.NEXTVAL,'Yazar3',CURRENT_TIMESTAMP()-3,'Kitap3',20,15,0);
INSERT INTO BOOK(ID, AUTHOR,CREATED_AT,NAME,STOCK,PRICE,VERSION) VALUES(BOOK_S.NEXTVAL,'Yazar4',CURRENT_TIMESTAMP()-4,'Kitap4',10,20,0);
INSERT INTO BOOK(ID, AUTHOR,CREATED_AT,NAME,STOCK,PRICE,VERSION) VALUES(BOOK_S.NEXTVAL,'Yazar5',CURRENT_TIMESTAMP()-5,'Kitap5',5,30,0);
INSERT INTO BOOK(ID, AUTHOR,CREATED_AT,NAME,STOCK,PRICE,VERSION) VALUES(BOOK_S.NEXTVAL,'Yazar6',CURRENT_TIMESTAMP()-6,'Kitap6',2,40,0);